### ISSUE TITLE
Problems with touchscreen

### ISSUE THREAD

**Issue by schoko11** [g200kg/input-knobs#2]
Hi and first thank you for this library in combination with webknobman this is really nice!

I tested knobs and switches for a local web project to control a hardware device by midi.
I use webmidi.js and bootstrap 5 and your input-knobs js file in a standard html5 template.

Using a Dell 24 touch screen on WIN10.
When touching a knob by hand i get an error:

```
Uncaught TypeError: ev.preventDefault is not a function at HTMLInputElement.ik.pointerdown(input-knobs.js:224)
ik.pointerdown @ input-knobs.js:224
```

tried to replace ev.preventDefault() with return false, but that does not seem to work.
(it does work on your example page, but i am not sure if / what's the difference )
Touching e.g. a switch works like expected.

Please give me a hint how to fix this, thank you!

**Comment by g200kg** [comment]
It is just a bug. Now Fixed.
Thank you for the report!

**Comment by schoko11** [comment]
Thanks, works nicely now
